### PR TITLE
Translate to ES the EN additions from #19

### PR DESCRIPTION
**Pull request by fadelkon**
that is, commits 492f41f1 and b3834df4

@llunaCreixent :eyes:

### CODE REVIEW

**Comment by fadelkon** [comment]
AGM I translated as "asamblea general", aunque no estoy seguro de que "internal meeting" encaje con eso.

**Comment by benhylau** [comment]
Thanks @fadelkon pls add yourself to the top "Traducido por"

**Comment by benhylau** [comment]
@fadelkon @llunaCreixent is this good to merge?

**Comment by llunaCreixent** [comment]
Yes, I wrote my change proposals as comments. If @fadelkon likes them, you can merge them :)

**Comment by llunaCreixent** [comment]
@fadelkon do likes my changes. you can merge, @benhylau

**Comment by benhylau** [comment]
Thanks @fadelkon @llunaCreixent merged with edits in #22

**Pull request closed without merging**
